[lint]
preview = true
select = ["ALL"]
ignore = ["ANN", "B", "C901", "COM812", "D", "E501", "E741", "EM101", "ERA001", "FBT", "I001", "N", "PD", "PERF", "PIE790", "PLR", "PT", "Q", "RET502", "RET503", "RSE102", "RUF001", "RUF012", "S", "SIM102", "SIM108", "SLF001", "TID252", "UP031", "TRY002", "TRY003", "TRY300", "UP038", "E713", "SIM117", "PGH003", "RUF005", "RET", "DTZ", "FIX", "TD", "ARG", "TRY400", "TRY200", "C408", "PLW2901", "PTH", "EM102", "INP001", "CPY001", "UP006", "UP007", "E266", "PIE808"]

[format]
preview = true
